-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100),
    CITY VARCHAR(100),
    CONTACT_EMAIL VARCHAR(150)
);

INSERT INTO CUSTOMERS
(CUSTOMER_ID, CUSTOMER_NAME, COUNTRY, CITY, CONTACT_EMAIL)
VALUES
(1, 'ALAN SMITH', 'UNITED STATES', 'NEW YORK', 'ALAN@EXAMPLE.COM'),
(2, 'AURORA TRADING', 'CANADA', 'TORONTO', 'AURORA@EXAMPLE.COM'),
(3, 'GLOBAL IMPORTS', 'GERMANY', 'BERLIN', 'GLOBAL@EXAMPLE.COM'),
(4, 'ORION RETAIL', 'AUSTRALIA', 'SYDNEY', 'ORION@EXAMPLE.COM'),
(5, 'NORDIC STORES', 'SWEDEN', 'STOCKHOLM', 'NORDIC@EXAMPLE.COM');

-- PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(100),
    UNIT_PRICE DECIMAL(10,2)
);

INSERT INTO PRODUCTS
(PRODUCT_ID, PRODUCT_NAME, PRODUCT_CATEGORY, UNIT_PRICE)
VALUES
(101, 'INDUSTRIAL SENSOR', 'ELECTRONICS', 125.50),
(102, 'SMART CONTROLLER', 'AUTOMATION', 299.99),
(103, 'POWER MODULE', 'ELECTRONICS', 89.75),
(104, 'WIRELESS GATEWAY', 'NETWORKING', 450.00);

-- EXPORTS TABLE
CREATE TABLE EXPORTS (
    EXPORT_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    EXPORT_COUNTRY VARCHAR(100),
    EXPORT_DATE DATE,
    QUANTITY INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

INSERT INTO EXPORTS
(EXPORT_ID, CUSTOMER_ID, PRODUCT_ID, EXPORT_COUNTRY, EXPORT_DATE, QUANTITY)
VALUES
(1001, 1, 101, 'UNITED STATES', '2025-01-15', 500),
(1002, 2, 102, 'CANADA', '2025-02-10', 300),
(1003, 3, 103, 'GERMANY', '2025-03-05', 700),
(1004, 4, 104, 'AUSTRALIA', '2025-04-20', 150),
(1005, 5, 101, 'SWEDEN', '2025-05-12', 250),
(1006, 4, 102, 'AUSTRALIA', '2025-05-25', 100);

-- CUSTOMER QUERYS
SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_NAME LIKE 'A%';

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_NAME LIKE '%OR%';

SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    P.PRODUCT_CATEGORY,
    P.UNIT_PRICE,
    E.EXPORT_COUNTRY,
    E.EXPORT_DATE,
    E.QUANTITY
FROM EXPORTS E
JOIN CUSTOMERS C
    ON E.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
    ON E.PRODUCT_ID = P.PRODUCT_ID
ORDER BY C.CUSTOMER_NAME;

SELECT
    C.CUSTOMER_NAME,
    P.PRODUCT_NAME,
    E.EXPORT_COUNTRY,
    E.QUANTITY,
    E.EXPORT_DATE
FROM CUSTOMERS C
JOIN EXPORTS E
    ON C.CUSTOMER_ID = E.CUSTOMER_ID
JOIN PRODUCTS P
    ON E.PRODUCT_ID = P.PRODUCT_ID
WHERE C.CUSTOMER_NAME LIKE 'A%'
   AND C.CUSTOMER_NAME LIKE '%OR%'
ORDER BY C.CUSTOMER_NAME;